stages:
  - artifact
  - deploy

before_script:
  - apk update && apk add git
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name "$GITLAB_USER_NAME"

# server-artifact:
#   image: alpine
#   stage: artifact
#   resource_group: artifact
#   script:
#     - apk add zip
#     - git clone --branch server-artifact https://deploy-token:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git server-artifact
#     - cd server-artifact
#     - rm -rf *
#     - cd ..
#     - zip -r server.zip .
#     - mv server.zip server-artifact
#     - cd server-artifact
#     - git add .
#     - git commit -m "$CI_COMMIT_AUTHOR commit $CI_COMMIT_DESCRIPTION with sha $CI_COMMIT_SHA" --allow-empty
#     - git push --force
#   only:
#     - dev

server-deploy:
  image: node:latest
  stage: deploy
  resource_group: deploy
  before_script: 
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm version $CI_COMMIT_TAG
    # - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish

