exports.seed = (knex) => knex('group_user')
  // Deletes ALL existing entries
  .del()
  // Inserts seed entries
  .then(() => knex('group_user').insert([
    {
      id: 1,
      owner_id: 1,
      user_id: 1,
      group_id: 1,
    },
    {
      id: 2,
      owner_id: 1,
      user_id: 2,
      group_id: 1,
    },
    {
      id: 3,
      owner_id: 1,
      user_id: 3,
      group_id: 1,
    },
    {
      id: 4,
      owner_id: 1,
      user_id: 4,
      group_id: 1,
    },
    {
      id: 5,
      owner_id: 1,
      user_id: 5,
      group_id: 1,
    },
    {
      id: 6,
      owner_id: 1,
      user_id: 6,
      group_id: 1,
    },
    {
      id: 7,
      owner_id: 1,
      user_id: 7,
      group_id: 1,
    },
    {
      id: 8,
      owner_id: 1,
      user_id: 8,
      group_id: 1,
    },
    {
      id: 9,
      owner_id: 1,
      user_id: 9,
      group_id: 1,
    },
    {
      id: 10,
      owner_id: 1,
      user_id: 10,
      group_id: 1,
    },
    {
      id: 11,
      owner_id: 1,
      user_id: 11,
      group_id: 1,
    },
    {
      id: 12,
      owner_id: 1,
      user_id: 12,
      group_id: 1,
    },
    {
      id: 13,
      owner_id: 1,
      user_id: 13,
      group_id: 1,
    },
    {
      id: 14,
      owner_id: 1,
      user_id: 14,
      group_id: 1,
    },
    {
      id: 15,
      owner_id: 1,
      user_id: 15,
      group_id: 1,
    },
    {
      id: 16,
      owner_id: 1,
      user_id: 16,
      group_id: 1,
    },
    {
      id: 17,
      owner_id: 1,
      user_id: 17,
      group_id: 1,
    },
    {
      id: 18,
      owner_id: 1,
      user_id: 18,
      group_id: 1,
    },
    {
      id: 38,
      owner_id: 1,
      user_id: 19,
      group_id: 1,
    },
    {
      id: 19,
      owner_id: 1,
      user_id: 1,
      group_id: 2,
    },
    {
      id: 20,
      owner_id: 1,
      user_id: 2,
      group_id: 2,
    },
    {
      id: 21,
      owner_id: 1,
      user_id: 3,
      group_id: 2,
    },
    {
      id: 22,
      owner_id: 1,
      user_id: 4,
      group_id: 2,
    },
    {
      id: 23,
      owner_id: 1,
      user_id: 5,
      group_id: 2,
    },
    {
      id: 24,
      owner_id: 1,
      user_id: 6,
      group_id: 2,
    },
    {
      id: 25,
      owner_id: 1,
      user_id: 7,
      group_id: 2,
    },
    {
      id: 26,
      owner_id: 1,
      user_id: 8,
      group_id: 2,
    },
    {
      id: 27,
      owner_id: 1,
      user_id: 9,
      group_id: 2,
    },
    {
      id: 28,
      owner_id: 1,
      user_id: 10,
      group_id: 2,
    },
    {
      id: 29,
      owner_id: 1,
      user_id: 11,
      group_id: 2,
    },
    {
      id: 30,
      owner_id: 1,
      user_id: 12,
      group_id: 2,
    },
    {
      id: 31,
      owner_id: 1,
      user_id: 13,
      group_id: 2,
    },
    {
      id: 32,
      owner_id: 1,
      user_id: 14,
      group_id: 2,
    },
    {
      id: 33,
      owner_id: 1,
      user_id: 15,
      group_id: 2,
    },
    {
      id: 34,
      owner_id: 1,
      user_id: 16,
      group_id: 2,
    },
    {
      id: 35,
      owner_id: 1,
      user_id: 17,
      group_id: 2,
    },
    {
      id: 36,
      owner_id: 1,
      user_id: 18,
      group_id: 2,
    },
    {
      id: 37,
      owner_id: 1,
      user_id: 19,
      group_id: 2,
    },
    {
      id: 39,
      owner_id: 1,
      user_id: 1,
      group_id: 3,
    },
    {
      id: 40,
      owner_id: 1,
      user_id: 2,
      group_id: 3,
    },
    {
      id: 41,
      owner_id: 1,
      user_id: 3,
      group_id: 3,
    },
    {
      id: 42,
      owner_id: 1,
      user_id: 4,
      group_id: 3,
    },
    {
      id: 43,
      owner_id: 1,
      user_id: 5,
      group_id: 3,
    },
    {
      id: 44,
      owner_id: 1,
      user_id: 6,
      group_id: 3,
    },
    {
      id: 45,
      owner_id: 1,
      user_id: 7,
      group_id: 3,
    },
    {
      id: 46,
      owner_id: 1,
      user_id: 8,
      group_id: 3,
    },
    {
      id: 47,
      owner_id: 1,
      user_id: 9,
      group_id: 3,
    },
    {
      id: 48,
      owner_id: 1,
      user_id: 10,
      group_id: 3,
    },
    {
      id: 49,
      owner_id: 1,
      user_id: 11,
      group_id: 3,
    },
    {
      id: 50,
      owner_id: 1,
      user_id: 12,
      group_id: 3,
    },
    {
      id: 51,
      owner_id: 1,
      user_id: 13,
      group_id: 3,
    },
    {
      id: 52,
      owner_id: 1,
      user_id: 14,
      group_id: 3,
    },
    {
      id: 53,
      owner_id: 1,
      user_id: 15,
      group_id: 3,
    },
    {
      id: 54,
      owner_id: 1,
      user_id: 16,
      group_id: 3,
    },
    {
      id: 55,
      owner_id: 1,
      user_id: 17,
      group_id: 3,
    },
    {
      id: 56,
      owner_id: 1,
      user_id: 18,
      group_id: 3,
    },
    {
      id: 57,
      owner_id: 1,
      user_id: 19,
      group_id: 3,
    },
  ]))
