#!/bin/bash
list=$(git diff --cached --name-only)
results=
for item in ${list[*]}; do
  cd .git/utilities/
  if [ -f ../../$item ]; then
  file=../../$item npm test
	results=$(file=../../$item npm test)
  results=$(echo $results | grep error)	
  fi
	if [ ! -z "$results" ]; then
		echo "### Ensure changes follow the Airbnb code style... ####"
		echo " "
		exit 1 # not committed
	else
		echo "Linting JS files successful."
		exit 0 
	fi
done
exit 1 # not committed
